---
#TODO: change this to    curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
#TODO: add    sudo apt-get install gitlab-runner
# - name: Download Gitlab runner
#   get_url: 
#     url : "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
#     dest: /tmp/gitlab-runner_amd64.deb

# - name: Install Gitlab runner
#   apt:
#     deb: /tmp/gitlab-runner_amd64.deb

- name: Download gitlab runner
  get_url: 
    url : https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: 'u+x,g+x'

- name: Install gilab-runner repo
  script:
    cmd: /tmp/script.deb.sh

- name: Install gitlab-runner
  apt:
    name:  "gitlab-runner"
    state: latest
    purge: yes
    update_cache: yes

- name: Register runner
  command: >
    gitlab-runner register 
    --non-interactive 
    --url '{{gitlab_server_url}}' 
    --registration-token '{{gitlab_runner_token}}'
    --description 'runner for laravel' 
    --tag-list '{{gitlab_runner_tag}}'
    --executor 'shell'

- name: Add gitlab-runner user to groups
  user:
    name: gitlab-runner
    groups: sudo,www-data,docker
    append: yes

- name: Add runner service to startup
  systemd:
    name: gitlab-runner
    state: started
    enabled: yes
    masked: no

- name: Add user "gitlab-runner" to sudoers
  lineinfile:
    path: /etc/sudoers.d/gitlab_runner
    line: 'gitlab-runner ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

#TODO: check npm installation and building
#TODO: add write right to group to /opt/rideonapp/.git/*
#TODO: add deploy key to gitlabrunner
# RUN mkdir -p /root/.ssh
# RUN touch /root/.ssh/deploy_key

# RUN echo """-----BEGIN RSA PRIVATE KEY-----""" >> /root/.ssh/deploy_key
# RUN echo """MIIEowIBAAKCAQEA5RffRP4gDgYwRQrJmfee8+bUAkQ51WEBgzfR/7x8gC2iqf/R""" >> /root/.ssh/deploy_key
# RUN echo """q+jqo3FgVNrfzHb9VrUPXk+OP7netczHrPu8Uw+hWbRfrEr1uzxTqjodKyPcrSy9""" >> /root/.ssh/deploy_key
# RUN echo """OQ+O9uJbC/xF6gL0xeg8s3ij0P6bpxFew+0OCyj+f4TcqdNHoaoR3yF4P+m4K1N/""" >> /root/.ssh/deploy_key
# RUN echo """H3XOagMRgA6/yeah5JAtBVLXBzG0pfZQRc0KVUMALR7AxgxrFwkUtNxvHkyjX+RO""" >> /root/.ssh/deploy_key
# RUN echo """3NbhIP9aHejTRVLhl4sVNd71T4WjBRNvlPtU6tLCfAUsCxMjVni0FStNGcF6jWHC""" >> /root/.ssh/deploy_key
# RUN echo """pS21Fv5WHjCi1u7+rX6tjstQ0Jfh1dC4AF6WAQIDAQABAoIBACbCczPpCuNUiLYl""" >> /root/.ssh/deploy_key
# RUN echo """rRYvnuUFGLmJcX94ehkJSK5L5YSKNAsvDPpY3dnpRLMWlOay+wnAeGksbJS7jcKU""" >> /root/.ssh/deploy_key
# RUN echo """cvQBY0tqSZIzwjwUMp8LBdy3GFhEKQHjn+AXkciTY3QTqoB9H4ycTijPMGgbq5oI""" >> /root/.ssh/deploy_key
# RUN echo """hk//u3CH7wcEI5FX/baMX5mwv/eP8XahmzLq+kpXlwSWtkmdB4/sRdKMqnBQovlr""" >> /root/.ssh/deploy_key
# RUN echo """xH01XLIFF03Xbs7/Q6SRD7ALa6gI74MaYqHWHTlFgt3QBQQ4BQPsLNqXdgcQBcMd""" >> /root/.ssh/deploy_key
# RUN echo """TUMm1PPcj/a0z3scJ5IrUwqt+XEFNPfns4QEL7H8xUfXT1eJBQ0uv/XfKXAW1h+5""" >> /root/.ssh/deploy_key
# RUN echo """iiGqrkECgYEA8iztMASY5S7Y+qZyI8luda/JoCb//WXviQVzgZSwI0kr1N9aD4Nd""" >> /root/.ssh/deploy_key
# RUN echo """oH0aWC2OlMhOdPQq/LHdizCqpHu8tKodNE7hOqQMd/lfOBN6L/r3k3tGpGyCfaFC""" >> /root/.ssh/deploy_key
# RUN echo """EVLkInErWhYh4FhhCqGsSuFb0aJk3+8s4tiH8Rt0JZYWtcwOGuTa4hMCgYEA8ivE""" >> /root/.ssh/deploy_key
# RUN echo """GLKMEziI/u0+KL0pF5bzHbQnVFfcI0SOrTzkJ4X0OsBQZ/gbViYy+pBIaTeYa3by""" >> /root/.ssh/deploy_key
# RUN echo """cmTE5sLUnS0A1V2WP6nKWAMhh1g6EdgJ6Me6DmUrPn45BrQrJOR7sr+ulZO5UpvG""" >> /root/.ssh/deploy_key
# RUN echo """dT/pIghHeaoM+xUAnhcACYzZlgE9bUWctNw8ChsCgYB8ZomcjfAAYnVBJDkjmvhr""" >> /root/.ssh/deploy_key
# RUN echo """6dXXt9Dt2OwX5b30xW1JYu/qFKWNrHxu0XSz8Qr58H8k4rwmPDPCqUgu4AUKhQwl""" >> /root/.ssh/deploy_key
# RUN echo """b5OQ7O4evvGju5Wbif6dOskJ81eAs1Jd1ceszZdoWlAijyOiM3Rurp7c69+HjLPw""" >> /root/.ssh/deploy_key
# RUN echo """/yuttd2O5S9bSavBMughEwKBgQC4Lrkx33nRlIn8+QrxiQybuF6nFMFk0H3JBPdO""" >> /root/.ssh/deploy_key
# RUN echo """oqUTujmKBYIh0P1ZhCv5jYrFG1d9RDYY8rMensd90yBzJn6DZOtUDO2PNnbT42+F""" >> /root/.ssh/deploy_key
# RUN echo """74F+OUuud+l/Q8AcivnZdRefA39LaNaDjlwNWiaiTccZn1uc4PlSSiGiiMbjOLJ6""" >> /root/.ssh/deploy_key
# RUN echo """i5XOSQKBgAMxyTHqolPAPupwyCwSf5YojyqWuv66zr3FIrkKawPFyJw8UBYbFnWF""" >> /root/.ssh/deploy_key
# RUN echo """HTk07vIEW4dx8+KoLMrNIZwH1eZtnQcjDEc/er9fMi4HQmJ3nmxGTjmWrYxNbHwh""" >> /root/.ssh/deploy_key
# RUN echo """bCNVMd8GYMoNTxFm61na8qGQ5aL5Skj5C4fD1XPB6S1U0bq/eMYx""" >> /root/.ssh/deploy_key
# RUN echo """-----END RSA PRIVATE KEY-----""" >> /root/.ssh/deploy_key

# RUN chmod 600 /root/.ssh/deploy_key

# RUN touch ~/.ssh/config

# RUN echo """Host gitlab.rideon.co""" >> ~/.ssh/config
# RUN echo """    HostName gitlab.rideon.co""" >> ~/.ssh/config
# RUN echo """    User deploy_user""" >> ~/.ssh/config
# RUN echo """    IdentityFile  ~/.ssh/deploy_key""" >> ~/.ssh/config
# RUN echo """    StrictHostKeyChecking no""" >> ~/.ssh/config
# RUN echo """    UserKnownHostsFile=/dev/null""" >> ~/.ssh/config

# Remove .bash_logout from gitlab-runner user profile